"""Generate the sympy-sstr print-order fixture for ax::sym to_sstr.

Each line: INPUT<TAB>SSTR where INPUT is parseable by both sympy and
axiom's parser and SSTR is sympy's canonical print of the parsed value.
Pinned: sympy 1.14, CPython 3.12/3.14 (cross-checked). Regeneration must
be a no-op diff. Output: tests/sym/fixtures/sstr_fixture.tsv
"""
import sys
from pathlib import Path

import sympy as sp
from sympy.parsing.sympy_parser import parse_expr

X = sp.Symbol("x")
LOCALS = {"x": X, "sin": sp.sin, "cos": sp.cos, "tan": sp.tan,
          "exp": sp.exp, "log": sp.log, "sqrt": sp.sqrt, "atan": sp.atan,
          "asin": sp.asin, "acos": sp.acos, "pi": sp.pi, "E": sp.E}

INPUTS = [
    # polynomials / rationals
    "5 + 2*x + x**3", "x - 5", "5 - x", "3 - x", "-x - 5", "x/2 + 3/4",
    "2/x + x**(-2)", "(x**2 - 1)/(x - 1)", "1/(2*sqrt(2 - x))",
    "x**(3/2) + sqrt(x) + x", "x**(-3/2)", "-x**2", "(-2)*x + 1",
    # function ladders
    "4*exp(x) - 7*sin(x) + 6*cos(x) + 5",
    "sin(x) + cos(x) + exp(x) + log(x) + sqrt(x) + atan(x) + x**2 + 3*x + 1",
    "asin(x) + acos(x) + atan(x) + tan(x)",
    "3*x*exp(x)*sin(x)", "7*x**2*log(2*x)**2",
    "x**2*sin(2*x + 1)*cos(3*x)", "exp(2*x)*sin(3*x)",
    "exp(2*x) + exp(x) + exp(3*x)",
    "sin(2*x) + sin(x)", "log(2*x) + log(x)",
    # quotients and monsters
    "log(x)/tan(3*x) + log(sin(3*x))/x",
    "(3 - 4*x)*sin(log(x*(2*x - 3)))",
    "(2*x - 3)*cos(log(x*(2*x - 3)))",
    "5*((3 - 4*x)*sin(log(x*(2*x - 3))) + "
    "(2*x - 3)*cos(log(x*(2*x - 3))))/(2*x - 3)",
    "6*sqrt(3)*sqrt(x**2)", "sqrt(2)*x + E*x + pi*x",
    "x**2*sin(x) + x**2 + x*sin(x) + x",
    "45*sqrt(2 - x) + 90/sqrt(2 - x) - (45*x + 180)/(2*sqrt(2 - x))",
    "9*log(x)/tan(3*x) + 3*log(sin(3*x))/x",
    "x*sin(log(4*x + 2)) + x*cos(log(4*x + 2))/2 - cos(log(4*x + 2))/4",
    "8*x**2*(log(x)/x - 1/(2*x)) + 9*x*(2*log(x)/x - 2/x)",
    "3*exp(x)*sin(2*x) + 6*exp(x)*cos(2*x)",
    "-cos(2*x + 1)/2", "-7*sin(x)", "-exp(x)*sin(x)",
    "sqrt(x**2)/x", "4*sqrt(x**2)*log(4*x + 3)",
    "1/x", "-1/x", "2/(3*x)", "x**2/2 + 7", "5/(2*x - 3)",
    "sin(x)**2 + cos(x)**2", "sin(x)**2*cos(x) + sin(x)**2 + 1",
    "(x + 1)**2*(x - 2)", "x*(x - 3)", "-(x - 3)*(x + 2)",
    "2**x", "3**(-x)", "x**x",
    "sqrt(7*x + 2)*cos(log(x + 1) + log(3))/(x + 1)",
    "atan(3*x)*log(x**2 + x + 1)",
    "exp(x)*sin(2*x)*cos(3*x)*x",
    "1 - x + x**2 - x**3",
]

out = Path(__file__).resolve().parent.parent / "tests" / "sym" / \
    "fixtures" / "sstr_fixture.tsv"
out.parent.mkdir(parents=True, exist_ok=True)
lines = ["# generated by scripts/gen_sstr_fixture.py on sympy "
         + sp.__version__ + " / CPython " + sys.version.split()[0]
         + " — regeneration must be a no-op"]
for s in INPUTS:
    e = parse_expr(s, local_dict=LOCALS, evaluate=True)
    lines.append(s + "\t" + sp.sstr(e))
out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print(f"wrote {out} ({len(INPUTS)} cases)")
