"""Generate the sympy count_ops parity fixture (Phase C task 1).

HCE and successor node-ordering depend on sympy-exact count_ops, so it
is fixture-gated like every parity surface. Rows: sstr<TAB>count_ops.
Inputs: mathgen L1-L8 draws + carrier-wrapped shapes + hand cases for
the DIV/NEG special counts. Pinned sympy 1.14. Regeneration must no-op.
"""
import random
import sys
from pathlib import Path

import sympy as sp

sys.path.insert(0, "/home/a/code/llmopt")
from llmopt.mathgen.problems import _expression  # noqa: E402

X = sp.Symbol("x")

rows = []


def add(e):
    rows.append((sp.sstr(e), int(sp.count_ops(e))))


# hand cases pinning the special counts
for e in [X, sp.Integer(5), -X, X + 1, X - 1, 2 * X, X / 2, 1 / X,
          X**2, X**-2, sp.sqrt(X), X * X, -2 * X + 1, (X + 1) / (X - 1),
          sp.sin(X), sp.sin(2 * X + 1), sp.exp(X) * sp.sin(X),
          sp.log(3 * X) ** 2, -sp.sin(X), 3 - X,
          sp.sqrt(2) * X + sp.pi * X + sp.E * X]:
    add(e)

# carrier-wrapped shapes (the search states)
f = X * sp.cos(X)
add(sp.Integral(f, X))
add(sp.Integral(f, X, X))
add(sp.Derivative(f, X))
add(sp.Integral(X * sp.exp(X), X) + sp.Integral(sp.sin(X), X))
u = sp.Symbol("_u")
add(sp.Subs(sp.Integral(sp.sin(u), u), u, X**2))
add(sp.Derivative(X**3 + 2 * X, X) - 3 * X**2)

# mathgen draws across the ladder
for level in range(1, 9):
    for seed in range(25):
        rng = random.Random(f"diff-{level}-{seed}")
        e = _expression(rng, level)
        add(e)
        add(sp.Integral(e, X))

out = Path("/mnt/c/Users/a/Documents/code/axiom/tests/sym/fixtures/"
           "count_ops_fixture.tsv")
out.parent.mkdir(parents=True, exist_ok=True)
lines = ["# generated by scripts/gen_count_ops_fixture.py on sympy "
         + sp.__version__ + " — regeneration must be a no-op"]
for s, c in rows:
    lines.append(f"{s}\t{c}")
out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print(f"wrote {out} ({len(rows)} rows)")
