"""Generate the CPython random.Random parity fixture for ax::pyrand.

Provenance: run against CPython (>=3.3 semantics: seed version 2 for
strings, _randbelow via getrandbits rejection sampling, shuffle via
reversed Fisher-Yates). Regenerating on any conforming CPython must be
a no-op diff. Cross-generated bit-exact on CPython 3.12.13 (llmopt WSL
farm) and 3.14.4 (axiom dev) on 2026-07-18 — both versions pinned.

Format (TSV, one stream per line): seed<TAB>stream<TAB>v1 v2 v3 ...
floats as repr() (shortest round-trip). Output:
tests/pyrand/fixtures/pyrand_fixture.tsv
"""
import hashlib
import random
import sys
from pathlib import Path

SEEDS = [
    "0", "42", "l6-sub-0.5405254639351326", "l7-sub-0.123",
    "l8-sub-0.9130110532378982", "level-3-seed-777",
    "the quick brown fox", "", "unicode-∂x",
]

out = Path(__file__).resolve().parent.parent / "tests" / "pyrand" / \
    "fixtures" / "pyrand_fixture.tsv"
out.parent.mkdir(parents=True, exist_ok=True)

lines = ["# generated by scripts/gen_pyrand_fixture.py on CPython "
         + sys.version.split()[0] + " — regeneration must be a no-op"]


def stream(seed: str, name: str, values) -> None:
    lines.append(f"{seed}\t{name}\t" + " ".join(str(v) for v in values))


for seed in SEEDS:
    stream(seed, "sha512_prefix",
           [hashlib.sha512(seed.encode()).hexdigest()[:32]])
    r = random.Random(seed)
    stream(seed, "random", [repr(r.random()) for _ in range(6)])
    r = random.Random(seed)
    stream(seed, "getrandbits",
           [r.getrandbits(k) for k in (1, 8, 31, 32, 33, 64)])
    r = random.Random(seed)
    stream(seed, "randint_1_9", [r.randint(1, 9) for _ in range(20)])
    r = random.Random(seed)
    stream(seed, "randint_m4_4", [r.randint(-4, 4) for _ in range(20)])
    r = random.Random(seed)
    stream(seed, "choice_5", [r.choice([0, 1, 2, 3, 4]) for _ in range(20)])
    r = random.Random(seed)
    xs = list(range(10))
    r.shuffle(xs)
    stream(seed, "shuffle_10", xs)
    # interleaved mixed-call trace: catches state-advance divergences that
    # per-method streams miss
    r = random.Random(seed)
    stream(seed, "mixed", [r.randint(1, 9), repr(r.random()),
                           r.choice([10, 20, 30]), r.getrandbits(33),
                           r.randint(-3, 3), repr(r.random())])

out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print(f"wrote {out} ({len(SEEDS)} seeds)")
